apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:
  name: auto-myapp

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 6
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50

