apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: myapp-rep-pod
      labels:
        app: myapp

    spec:
      containers:
        - name: nginx-container-replica
          image: nginx
    
  replicas: 3

  selector:
    matchLabels:
      app: myapp



