apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: backend

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp

    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.3

  replicas: 3

  selector:
    matchLabels:
      app: myapp
