apiVersion: v1
kind: Pod

metadata:
  name: pod-pvc
 

spec:
  containers:
    - name: nginx-container
      image: nginx

      volumeMounts:
        - mountPath: /data
          name: pv-test-storage
 
  volumes:
    - name: pv-test-storage
      persistentVolumeClaim:
        claimName: pvc-test

      

       