apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-test
  labels:
    type: local

spec:
  storageClassName: standard
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
 
  hostPath:
    path: "/tmp/pv-volume"