apiVersion: v1
kind: Pod

metadata:
  name: get-secret

spec:
  containers:
    - name: env-printer
      image: nginx

      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username

        - name: password
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password

        - name: API_URL
          value: https://api.com

       