apiVersion: batch/v1

kind: CronJob

metadata:
  name: helloworld-job

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command: ["echo","Hello World"]
          
          restartPolicy: Never

          