apiVersion: batch/v1

kind: Job

metadata:
  name: helloworld-job

spec:
  #completions: 10
  #parallelism: 2
  #backoffLimit: 2
  activeDeadlineSeconds: 10
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          #command: ["echo","Hello World"]
          #command: ["ls","/tt"]
          command: ["sleep","60"]

      restartPolicy: Never

          